spring.application.name=order-processing

spring.datasource.url=jdbc:mysql://localhost:3306/OPS
spring.datasource.username=Admin
spring.datasource.password=Admin

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
processing.timeout.minutes=5
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.pattern.level=%5p [corrId:%X{correlationId}]

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=order-group
spring.kafka.consumer.auto-offset-reset=earliest